name: Code Scan

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        id: bandit
        run: bandit -r .

      - name: Check Bandit Results
        run: |
          if grep -q "CVSS:3.0/CRITICAL" bandit_results.txt; then
            echo "::error::Critical or above vulnerabilities found. Blocking the pull request."
            exit 1
          else
            echo "No critical or above vulnerabilities found. Allowing the pull request to proceed."
          fi
