name: Security Scan

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        id: bandit
        run: |
          bandit -r . > bandit_results.txt || true
          echo "::set-output name=has_critical_vulnerabilities::$(grep -q 'Severity: CRITICAL' bandit_results.txt && echo true || echo false)"
          cat bandit_results.txt
          
      - name: Check for Critical Vulnerabilities
        run: |
         if [ "$HAS_CRITICAL_VULNERABILITIES" == "true" ]; then
          echo "Critical vulnerabilities found. Blocking the pull request."
         else
          echo "No critical vulnerabilities found. Merging the pull request."
         fi
      
        
    


      
